# Generated by Django 3.2 on 2021-09-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_alter_favorite_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
