# Generated by Django 3.2 on 2021-09-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_auto_20210905_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='image',
            field=models.ImageField(upload_to='image'),
        ),
        migrations.AlterField(
            model_name='film',
            name='sam_film',
            field=models.FileField(upload_to='sam_film'),
        ),
    ]
